export const english = {
    error: 'Error',
    failedToLoadTheSound: 'Failed to load the sound. \n Possibly due to no internet connection.', //Sound.js
    noWordFound: 'No word found or typo.', //dictionary.js
    couldNotFinishTheQuery: "Couldn't finish this query due to a possible bug. Please contact the developer.",
    connectionErrorContact: "Connection error or Request timed out.",
    selectADictionary: 'Select a dictionary',
    databaseConnectionError: 'Database Connection Error',
    saved: 'Saved',
    successfullySavedTo: 'Successfully saved to "',
    successfullySavedToJapanese: '".',
    duplicateFoundChooseDifferentFolder: 'Duplicate was found in the folder. Choose a different folder.',
    dataRetrievedFromEJDict: 'Data retrieved from "ejdict-hand" https://github.com/kujirahand/EJDict',
    dataRetrievedFromWikitionary: 'Data retrieved from Wiktionary',
    searchResultShownHere: 'Search results will be shown here.',
    showResult: 'Show result  ',
    loading: 'Loading...',
    selectAFolderToSave: 'Select a folder to save',
    noFolderCreateFirst: 'No folder. Create a folder first.',
    lookUpAWord: 'Look up a word (Type exactly)',
    failedToSaveConfig: 'Failed to save the configuration', //SelectFavDictionary.js
    settings: 'Settings',//SettingPage.js
    about: 'About', 
    guide: 'Guide to the app',
    version: 'Version',
    dictionary: 'Dictionary',
    defaultDict: 'Default dictionary',
    favDict: 'Favourite dictionaries',
    others: 'Others',
    contactUs: 'Contact us',
    termsAndConditions: 'Terms and conditions',
    privacyPolicy: 'Privacy policy',
    selectADictionaryToDefault: 'Select a dictionary to set to default',
    errorOpeningFolder: 'Error while opening folder.', //BrowseFolder.js
    browsing: 'Browsing "',
    noCardInFolder: 'No card in this folder',
    createdSuccessfully: 'Created Successfully!', //CustomCard.js
    errorSaving: 'Error while saving card.',
    errorReloadingScreen: 'Error while reloading screen',
    createACard: 'Create a card',
    typeAWordHere: 'Type a word here',
    typeDefinitionAnswer: 'Type the definitions of the word here (Answer)',
    editedSuccessfully: 'Edited Successfully!', //EditCard.js
    errorEditingCard: 'Error while editing the card',
    edit: 'Edit',
    typeDefinition: 'Type the definition of the word here',
    typeTypeOfSpeech: 'Type the part of speech of this definiton',
    typeExampleSentence: 'Type example sentences of this definition',
    origin: 'Origin:',
    typeWordOrigin: 'Type the word origin here',
    setLevel: 'Set level...',
    selectLevel: 'Select level',
    label0: 'Reset to default (from lv.0)',
    label1: 'in 1 Minute (lv.1)', 
    label2: 'in 10 Minutes (lv.2)',
    label3: 'in 1 day (lv.3)',
    label4: 'in 4 days (lv.4)', 
    label5: 'in 1 week (lv.5)', 
    label6: 'Complete (lv.6)', 
    folders: 'Folders',//folderpage.js
    createFolder: 'Creating a folder', 
    setNewFolderName: 'Set the name of a new folder...',
    failedCreateFolder: 'Failed to create a folder.',
    setValidName: 'A folder name cannot be empty. Set a valid name.',
    folderNameDuplicate: 'Another folder with the same name already exists. Try another name.',
    confirm: 'Confirm',
    areYouSureToDeleteGone: 'Are you sure to delete? \n All data in the folder will be gone.',
    errorDeletingFolder: 'Error while deleting the folder',
    editFolderName: 'Editing the folder name',
    insertFolderName: 'Insert the new name...',
    editValidFolderName: "A folder name needs to be different from the previous or the other folder's name. \n\n Try another name.",
    failedEditingFolderName: 'Editing the folder name failed. Please contact the app developer.',
    noFolder: 'No folder',
    deleteSelectedWords: 'Delete Selected Cards', //handleSelectedWord.js
    deleteAll: 'Delete All',
    transferSelectedWords: 'Transfer Selected Cards',
    transferAll: 'Transfer All', 
    resetAllLevels: 'Reset All Levels', 
    cancel: 'Cancel',
    noCardsSelected: 'No cards are selected',
    areYouSureToDelete: 'Are you sure to delete?',
    errorDeletingCards: 'Error while deleting cards',
    areYouSureToReset: 'Are you sure to reset level of all cards? \n All progress on this folder will be lost.',
    areYouSureToTransfer: 'Are you sure to transfer to "',
    areYouSureToTransferJapanese: '"?',
    duplicatesFoundTransferAreYouSure: 'Duplicates were found. Are you still sure to transfer all to "',
    duplicateFoundYouMightLose: '"? \n\n You might lose some of your edited cards.',
    areYouSureToTransferAll: 'Are you sure to transfer all to "',
    areYouSureToTransferAllJapanese: '"?',
    select: 'Select...',
    selectAFolderToTransfer: 'Select a folder to transfer',
    level: 'level...',
    startMemorizing: 'Start memorising...', //memorisepage.js
    errorUpdatingFolder: 'Error updating folder', //swipeCard.js
    congraturations: 'Congratulations!',
    clearedThisCard: 'You cleared this card.',
    finished: 'Finished',
    finishedDetail: 'You finished your task on this folder for now!',
    buttonNo: 'No',
    buttonSoSo: 'So-so',
    buttonGood: 'Good',
    answer: 'Tap here to check the answer',
    memorise: 'Memorise !',
}