export const japanese = {
    error: 'エラー',
    failedToLoadTheSound: '音声のロードに失敗しました。 \n インターネットに接続できない為である可能性があります。', //Sound.js
    noWordFound: '検索の結果、見つかりませんでした。誤字はありませんか？', //dictionary.js
    couldNotFinishTheQuery: "このクエリはバグにより失敗した可能性があります。開発者に報告をお願いします。",
    connectionErrorContact: "接続エラーか、リクエストがタイムアウトしました。",
    selectADictionary: '辞書を選択',
    databaseConnectionError: 'データーベース接続エラー',
    saved: '保存完了',
    successfullySavedTo: '"',
    successfullySavedToJapanese: '"に保存しました。',
    duplicateFoundChooseDifferentFolder: 'このフォルダには同じカードがあります。他のフォルダを選択してください。',
    dataRetrievedFromEJDict: 'データ取得元: "ejdict-hand" https://github.com/kujirahand/EJDict',
    dataRetrievedFromWikitionary: 'データ取得元: Wiktionary',
    searchResultShownHere: 'ここに検索結果が表示されます。',
    showResult: '検索  ',
    loading: 'ロード中...',
    selectAFolderToSave: '保存するフォルダを選択してください。',
    noFolderCreateFirst: 'フォルダがありません。先にフォルダを作成してください。',
    lookUpAWord: '単語を入力',
    failedToSaveConfig: '設定の保存に失敗しました。', //SelectFavDictionary.js
    settings: '各種設定',//SettingPage.js
    about: 'About', 
    guide: '操作説明(英語)',
    version: 'バージョン',
    dictionary: '辞書設定',
    defaultDict: 'デフォルト辞書',
    favDict: 'よく使う辞書',
    others: 'その他',
    contactUs: '開発者に報告',
    termsAndConditions: '利用規約',
    privacyPolicy: 'プライバシーポリシー',
    selectADictionaryToDefault: '辞書をデフォルトに設定',
    errorOpeningFolder: 'フォルダを開けませんでした。', //BrowseFolder.js
    browsing: '閲覧中: "',
    noCardInFolder: 'このフォルダには何もありません。',
    createdSuccessfully: '作成完了！', //CustomCard.js
    errorSaving: '保存に失敗しました。',
    errorReloadingScreen: 'リロードに失敗しました。',
    createACard: 'カードを作成',
    typeAWordHere: '単語を入力',
    typeDefinitionAnswer: '意味(答え)を入力',
    editedSuccessfully: '編集完了！', //EditCard.js
    errorEditingCard: '編集に失敗しました。',
    edit: '編集',
    typeDefinition: 'ここに意味を入力してください。',
    typeTypeOfSpeech: 'ここに品詞を入力してください。',
    typeExampleSentence: 'ここに例文を入力してください。',
    origin: '語源:',
    typeWordOrigin: 'ここに語源を入力してください。',
    setLevel: 'レベル設定',
    selectLevel: 'レベルを選択',
    label0: 'デフォルト(lv.0)',
    label1: '1分後 (lv.1)', 
    label2: '10分後 (lv.2)',
    label3: '1日後 (lv.3)',
    label4: '4日後 (lv.4)', 
    label5: '1週間後 (lv.5)', 
    label6: 'マスター (lv.6)', 
    folders: 'フォルダ',//folderpage.js
    createFolder: 'フォルダ作成', 
    setNewFolderName: 'フォルダの名前を設定してください。',
    failedCreateFolder: 'フォルダの作成に失敗しました。',
    setValidName: '空のフォルダ名は無効です。有効な名前を入力してください。',
    folderNameDuplicate: '同じ名前のフォルダが存在しています。別の名前を入力してください。',
    confirm: '警告',
    areYouSureToDeleteGone: '本当に削除しますか？ \n このフォルダ内のデータは全て削除されます。',
    errorDeletingFolder: 'フォルダの削除に失敗しました。',
    editFolderName: 'フォルダ名の編集',
    insertFolderName: '新しい名前を入力してください。',
    editValidFolderName: "以前のフォルダ名や既存のフォルダ名とは別の名前を入力してください。",
    failedEditingFolderName: 'フォルダ名の編集に失敗しました。開発者に報告をお願いします。',
    noFolder: 'フォルダがありません。',
    deleteSelectedWords: '選択したカードを削除', //handleSelectedWord.js
    deleteAll: '全てのカードを削除',
    transferSelectedWords: '選択したカードを移動',
    transferAll: '全てのカードを移動', 
    resetAllLevels: '全てのレベルをリセット', 
    cancel: 'キャンセル',
    noCardsSelected: 'カードが選択されていません。',
    areYouSureToDelete: '本当に削除しますか？',
    errorDeletingCards: 'カードの削除中にエラーが発生しました。',
    areYouSureToReset: '本当に全てのカードのレベルをリセットしますか？ \n これまでの復習記録は全て失われます。',
    areYouSureToTransfer: '本当に"',
    areYouSureToTransferJapanese: '"にカードを移動しますか？',
    duplicatesFoundTransferAreYouSure: '同じ単語カードが見つかりました。本当にカードを"',
    duplicateFoundYouMightLose: '"に移動しますか？ \n\n 編集済のカードが失われるかもしれません。',
    areYouSureToTransferAll: '本当に全てのカードを"',
    areYouSureToTransferAllJapanese: '"に移動しますか？',
    select: '選択...',
    selectAFolderToTransfer: '移動先のフォルダを選択',
    level: 'レベル...',
    startMemorizing: '復習を開始',
    errorUpdatingFolder: 'フォルダの更新に失敗しました。', //swipeCard.js
    congraturations: '復習完了！',
    clearedThisCard: 'このカードをクリアしました。',
    finished: '復習完了',
    finishedDetail: 'このフォルダのタスクを完了しました。お疲れさまでした。',
    buttonNo: '全然',
    buttonSoSo: '微妙',
    buttonGood: 'OK',
    answer: 'タップして答えを確認',
    memorise: `Let's 復習!`,
}